### ISSUE TITLE
Criar Classe Gráfico

### ISSUE THREAD

**Issue by kassiacatarine** [DemandaFacil/DemandaFacil#12]
## Contexto
Criar uma classe gráfico para que seja possível instancia-la em outra classe, podendo passar os valores que serão plotados no gráfico.

## Referencia
Existe muitos sites falando sobre geração de gráfico, a seguir segue um exemplo:
http://www.caelum.com.br/apostila-java-testes-xml-design-patterns/graficos-com-jfreechart/

**Comment by rastamarco** [comment]
Estou fazendo \o
