### ISSUE TITLE
Média Móvel Ponderada

### ISSUE THREAD

**Issue by kassiacatarine** [DemandaFacil/DemandaFacil#13]
## Entrada:
ArrayList de Consumo
Opção de quantidade de prazo(Curto, Medio, Longo, ValorInformado)

## Saída:
Valor Calculado (Int)

## Contexto:

Eu como máquina, recebo um ArrayList de Consumo de um produto, chamo um método para ele achar todos os períodos recentes e recebo um novo ArrayList com os valores que serão usados para o calculo.
Consumos = ({id, data, quantidade}, ...}

Os pesos serão padrão nesse inicio de projeto, utilizar valores crescentes entre 0 até 1, sendo que quanto mais próximo ao consumo final mais próximo será do peso 1.

A partir desse ArrayList eu calculo a Média Móvel Ponderada de acordo com o prazo especificado e retorno o valor calculado.

**Comment by NicolasAoki** [comment]
meu
