### ISSUE TITLE
Média Móvel Simples

### ISSUE THREAD

**Issue by kassiacatarine** [DemandaFacil/DemandaFacil#6]
## Entrada:
ArrayList de Consumo
Opção de quantidade de prazo(Curto, Medio, Longo)

## Saída:
Valor Calculado (Int)

## Contexto:

Eu como máquina, recebo um ArrayList de Consumo de um produto, chamo um método para ele achar todos os períodos recentes e recebo um novo ArrayList com os valores que serão usados para o calculo.
Consumos = ({id, data, quantidade}, ...}

A partir desse ArrayList eu calculo a Média Móvel Simples de acordo com o prazo especificado e retorno o valor calculado.

## Relacionado:
#11

**Comment by bforcato** [comment]
Eu faço
